### ISSUE TITLE
Layer blending and filter effects

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#1212]
Since each layer in a map can be treated as a separate HTML element (canvas), it is possible to manipulate the graphics of each layer through various CSS [blending modes](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode) and [graphics filters](https://developer.mozilla.org/en-US/docs/Web/CSS/filter). For example, one can blend two background maps to create pretty hybrid backgrounds or manipulate brightness, contrast, hue, saturation etc.

I think it would be nice to implement this as configurable layer settings.

![image](https://user-images.githubusercontent.com/15725608/112490397-a09def00-8d7f-11eb-9a46-bbf5dfad9429.png)
*Two WMS layers with blending mode **multiply** set on the top layer and **brightness** and **contrast** filters set on the bottom layer to make it pop a little*

**Comment by jokd** [comment]
Checked into this a bit and maybe we should use classes anyway:
![image](https://user-images.githubusercontent.com/6848075/113249241-a84d1e80-92be-11eb-8453-3e89b235375d.png)
That is also supported out-of-the-box ("className": "somniceclass") since the layer config object are used when creating the layers. 
We could add "cssStyle": { "someniceclass": { mix-blend-mode: darken; } } and then add all cssStyle objects to the maps css.
But that will make it harder to change an individual layers blending modes/css filters.

Another way to do it is to use inline styling along with a unique, nonsense, className to prevent multiple layers being rendered in the same html element when using some css witchcraft.

**Comment by jokd** [comment]
Either way works for me but if we (intend to) make this an editable option like the opacity all layers must be separate html elements and thats obviously not the best from a performance perspective. But if we want that option, perhaps the layer can be rerendered with a className when changing that setting. I can't see why it should be used frequently so it is not that big issue.

**Comment by tonnyandersson** [comment]
Perhaps only setting a `className` if the layer has filter or blending options? That way there's no need to rerender. And the `className` property _must_ be used in one way or another, either for applying css properties to that class or for grabbing and manipulating the element in question. AFAIK, you can't get the layer's HTML element though OL layer properties only.

**Comment by jokd** [comment]
I meant if the layer initally haven't got any css magic but the user has the option to set it, it must then get a className if the user changes the setting.

**Comment by tonnyandersson** [comment]
Ah, true.
