### ISSUE TITLE
Show webpage in infowindow

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1364]
**Is your feature request related to a problem? Please describe.**
It would be nice to show a webpage in infowindow for a feature that has some report made in some external system.

**Describe the solution you'd like**
In attributes for a layer it should be able to configurate a attribute is a url that is to be shown as a webpage in the popup for the featureinfo, see mockup with estate info:
![image](https://user-images.githubusercontent.com/48793206/137084383-63809200-4478-42ba-81aa-cd490a89ed56.png)

**Comment by Flodkvist** [comment]
I´ve been thinking of similar things.

I tried using the html attribute with "out of the box" origo, this is what it looks like with the content I would like to show.

![image](https://user-images.githubusercontent.com/31692548/137105733-6ffe0610-4205-4f6c-ad09-e885ee371d6f.png)

I´ve been thinking of maybe making a new type of popup available, like the fullscreen modal with a vertical separator where the left side looks like the default popup and the right side available for somethink like an iframe based on settings. 
Maybe being able to change the content on the right side by clicking on links in the left, loading new/other iframe/links.

![image](https://user-images.githubusercontent.com/31692548/137108301-7241d15f-fb86-48bc-a894-d554bff1b8cd.png)


I have a case where it would be usefull to add similar functions to the editor as well.

**Comment by johnnyblasta** [comment]
> Why not use the existing `html` attribute type? Like:
> 
> `"html": "<iframe src='https://myembeddedwebpage.org'...></iframe>"`
> 
> ...or, if there's an attribute with a URL:
> 
> `"html": "<iframe src='{{myEmbeddedWebpageUrlAttribute}}'...></iframe>"`

That is basically what I did when doing the mockup, but also changed the width and height of the popup to make it look good. So it can work as is if it is now only with the possiblity to control the size of the popup.

**Comment by tonnyandersson** [comment]
@johnnyblasta Yeah, we had the exact same discussion yesterday regarding options to set the size of the popup in the config, or even better, a fully dynamic popup that adapts to its content. But I guess the latter might be hard to achieve because of things like the image carousel and such. Haven't looked into it, but my gut tells me there's something in there that needs a fixed width as reference somewhere.

For links you can always use a [modal as target](https://github.com/origo-map/origo/pull/777). No need to make it fullscreen, just go with `"target": "modal"`. Perhaps it would be a good idea to make the modal draggable, though. And make the size configurable.

@Flodkvist, perhaps this is the way to go in your case? I do like your idea of a "sidebar" showing the webpage, but I'm not sure it would work very well on smaller devices.

**Comment by Flodkvist** [comment]
@tonnyandersson  My use case is rather unusual and will probably require other tweaks as well so I agree, no further discussion on my mockup is necessary.

The popup is maybe complex enough as it is and messing with it is perhaps more trouble then its worth.
Width settings of sidebar, size settings of modal and draggble modal would be a nice additions though.

**Comment by johnnyblasta** [comment]
Closing this since there are other ways of accomplish it.
