### ISSUE TITLE
Search control zoom to wrong location

### ISSUE THREAD

**Issue by Owemyr** [origo-map/origo#1405]
**Describe the bug**
In latest origo-master search control fails to zoom to the correct location/feature.
It fails only when feature location is not in current extent. 
When i revert Attachments PR #1372 it works fine again.

**Screenshots**
As seen in the gif, first search when feature is inside extent works but second fails.
![search_probs_2021-12-15_6](https://user-images.githubusercontent.com/47249045/146188041-c75a6d9d-6d0f-41ee-990a-c9cb475f8601.gif)

**Additional context**
Origo-server is used as backend for search control.

**Comment by steff-o** [comment]
Hmm. As writer of #1372 I do feel responsible.

I don't have a search endpoint to test against right now. But the problem seems to be that #1372 turned the render() function into an async-ish operation, which effectively reverses the execution order of doRender and zoomToExtent in the search control. Didn't think that it would matter, as the result of render is never waited for and was previously treated as an async fire and forget anyway as the panning occurs after the call to render has returned. But now the zoomToExtent call is executed before the doRender() function, and then render tries to pan to where the popup should be. Not sure why it ends up in the wrong place though as the popup itself is placed correctly.

That said, we must fix it of course. One way would be to actually make render return a promise so it can be awaited for. Another way could be reversing the call order in showFeatureInfo() in search.js, so zoomToExtent() is called before render tries to pan the popup into view. If it already zoomed to it wouldn't have to be panned to. But that's pretty much the situation today, so that may not fix it. Another solution would be changing render() to only execute Promise.all when there actually is something to await, but that would lead to inconsistent behavior depending on if attachments are present or not.

**Comment by jerlob** [comment]
How is this issue going? Anybody working on a solution?

**Comment by steff-o** [comment]
I might give it a stab tomorrow.
