### ISSUE TITLE
Icons rescaled after print

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#1476]
**Describe the bug**
When using scaled symbols in the map, the scale seems to be overlooked when re rendering the map after the print preview.
Eg:
```
		"symbol": [
			[{
				"icon": {
					"size": [64, 64],
					"src": "icon.png",
					"scale": 0.5
				}
			}]
		],
```

**Screenshots**
Before print:
![image](https://user-images.githubusercontent.com/6848075/155306006-d6d94886-5b3f-42f5-baba-9200f35a4ad7.png)

After:
![image](https://user-images.githubusercontent.com/6848075/155306076-2ea68131-f435-40eb-88a1-695db24ebdbf.png)

Ideas on this @Grammostola ?

**Comment by jokd** [comment]
Had a go at it but I am probably destroying something since it was written a bit more complicated from the beginning:
https://github.com/origo-map/origo/tree/print-scale-fix

**Comment by Grammostola** [comment]
I have been unable to make your initial suggestion do what I think is intended, my current thought is that the (original) style scale can be fetched from the viewer  and then loop through every feature and update as is currently done (but with the original scale number instead of 1). (A stray thought was a kind of memory at SetLayerScale() but it may not be necessary). I hope to be able to spend some more time with this next week.

**Comment by Grammostola** [comment]
This seems to work for icons using a scale param in their style (this issue)
```javascript
    if (isVector(layer)) {
      const styleName = layer.get('styleName');
      const styles = viewer.getStyle(styleName);
      if (styleName && styles && styles.length === 1) {
        const newStyle = Style.createStyle({
          style: styleName,
          viewer
        })();
        if (newStyle) {
          source.getFeatures().forEach(feature => {
            feature.setStyle(newStyle);
          });
        }
      }
    }
```
however it is as much responsible for the related issue as the current setLayerScale function (entering the print preview)
so I have an alternate solution in the works

**Comment by Grammostola** [comment]
The alternate solution for this issue and resetLayerScale() needed the selection-robbing setStyle() in setLayerScale() in order to not be selection-robbing, it turns out. I haven't been able to getStyle() of a feature prior to setStyle() on said feature, even if the feature logged seems to have a style_ property before setStyle().

 There is a "selected" property of selected features however that I might be able to use.
