### ISSUE TITLE
Print - incorrect style for highlighted/selected objects after print

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1482]
**Describe the bug**
When you return to the map after printing, the style of the selected item is incorrect.

**To Reproduce**
1. Go to print
2. Close print
3. Select an object

**Expected behavior**
The selected object should have the style (or default style) from the json file.

**Screenshots**

![print-selected-style-issue](https://user-images.githubusercontent.com/17123002/156345046-06b5ecbd-7394-4630-b856-cc2496c52a6b.gif)

**Additional context**
Related to https://github.com/origo-map/origo/issues/1476?

**Comment by jokd** [comment]
Seems related, @Grammostola

**Comment by sonjahalmstad** [comment]
We get the same problem!
![Printproblem_](https://user-images.githubusercontent.com/14833158/156367107-c74c605c-6e48-4d74-89d8-47be56000445.gif)

**Comment by Grammostola** [comment]
Acknowledged. It seems the selection goes missing on print preview entry rather than exit and the fix I'm evaluating for the other print bug does not affect this issue. (Neither does suppressNewDPIMethod, unfortunately). I agree that both are bad, I will finish constructing the PR for the other issue first and can't promise that I will return to this one before the week is out since mostly meetings but will have a look at asap.

**Comment by Grammostola** [comment]
It seems to not be an issue with theme (wfs) layers; they are treated differently. "Changing the scale of all features' styles" isn't a functional idea because a feature won't respond to getStyle() if inherited from its layer rather than being subjected to setStyle(). Unless someone acts quicker or sees an issue with the idea I will look into whether treating wfs layers with non-theme styles like those with theme styles are now is an alternative.
