### ISSUE TITLE
Use style from WMS server

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1560]
**Is your feature request related to a problem? Please describe.**
When you have a WMS layer and the style in the map comes from the WMS server and the Origo style in the config is basically a URL to the GetLegendGraphic call from the server. It would simplify things if it was possible in the layer config to say just to get the legend graphics from the server. Then there is no need to setup a style for the layer in the config, which reduces administration of styles and less places to make edits if for say the adress to the server is changed f.e. switching between test and production servers.

**Describe the solution you'd like**
On the layer config there should be a option to say that the style should be fetched from the server.

**Describe alternatives you've considered**
I guess the option should include more settings such as the possibility to use an alternative style other than the default. Also extendedLegend should be able to set. 
In print legend there is a similar function with GetLegendGraphic call one could look at.

**Comment by jokd** [comment]
We recently had exactly this discussion (and request) and had a look at karta.eskilstuna.se where they have implemented this in a nice way. I think that is a part of their legend enhancer-plugin, but this feels definitely like a feature for the core.
@Grammostola Words on this?

**Comment by Grammostola** [comment]
Yes, it's part of the legend-enhancer plugin , https://github.com/Eskilstuna-kommun/legend-enhancer/blob/master/src/legendenhancer/styleSetter.js . It works if no style is specified for a (wms) layer and fetches a theme composite image for theme layers. The print-legend fetches individual rules. Both are geared towards Geoserver (the former used getLegendGraphic as application/json for checking whether theme layer (and extendedLegend) and the latter for finding the rules of the style). 

A solution for Origo could be limited to Geoserver (and perhaps ArcGIS Server what with the current PR about print theme layers) initially with further map server support welcome?

**Comment by steff-o** [comment]
Maybe its possible to utilise https://openlayers.org/en/latest/apidoc/module-ol_source_ImageWMS-ImageWMS.html#getLegendUrl

Adding to @Grammostola s comment, perhaps some configuration may come in handy:
- Telling if it is a composite layer or not if it can not be determined automatically for all kinds of servers
- Size and scale hints and whatever arguments _getLegendGraphic_ supports

The configuration parameters would of course be optional and default to the most common sane stuff in order to keep configuration to a minimum. You would still benefit from not having to configure the actual URL even if some parameters have to be set in some cases.
