### ISSUE TITLE
Measure tool distance problem

### ISSUE THREAD

**Issue by David0099** [origo-map/origo#1617]
**Describe the bug**
Problem with measure tool, not getting the correct distance.

I used the measure tool to measure buildings (using snap) and noticed that I did not receive the same distance-result as in other software we use (QGIS and Topocad)
For example the result on a 20 meter building differed about 5 cm. 

**Screenshots**
![Origo](https://user-images.githubusercontent.com/52694843/196150142-cc7139b8-a6f7-43d5-aae9-cceaaf4e119f.JPG)
Origo

![QGIS](https://user-images.githubusercontent.com/52694843/196150164-920fdb5d-6849-482d-9fd1-b994455d56bc.JPG)
QGIS

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Comment by jokd** [comment]
I can verify this and here are discussions on the subject:
https://github.com/openlayers/openlayers/issues/9141
https://github.com/openlayers/openlayers/pull/13572

**Comment by jokd** [comment]
> Is there anything we can do in Origo to achieve higher accuracy? If not, perhaps this issue can be closed.

We can implement another library but obviously adds size to the core. Maybe a plugin is the way to go?

**Comment by tonnyandersson** [comment]
Closing this since it's mostly an OL issue. Based on the information found in the links provided by @jokd above, there are various ways to solve this issue but all of them seem to require third party libraries to do the heavy lifting.

For now, if anyone feel the need of desktop GIS levels of accuracy in Origo we suggest you develop a plugin utilizing such libraries.
