### ISSUE TITLE
Print - PDF export not working properly in IOS Safari

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#1619]
**Describe the bug**
PDF export is a bit sketchy in IOS Safari. The map is sometimes blank in the export and sometimes present but with the top-left corner anchored to the center of the layout.

**To Reproduce**
1. Open an Origo map (master version) in IOS Safari
2. Open print control
3. Choose PDF export

**Smartphone (please complete the following information):**
 - Device: Iphone 7
 - OS: IOS 15.7
 - Browser: Safari

**Additional context**
Works fine on Android device.

**Comment by jokd** [comment]
I hav been testing this and there are two (maybe related) issues I can identify. The first is that there is no print preview on iOS when the canvas is bigger than a certain size (on iPhone 12 max resolution is ~138ppi for A4 print)
The second is the library used for creating image from the DOM is really unstable on iOS and often return empty maps.
My suggestion is that we use html2canvas instead of dom-to-image-more. There are some styling issues that I think we can handle.
