### ISSUE TITLE
Hide mapmenu when embedded results in error

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/origo#1632]
**Describe the bug**
When setting the mapmenu `"hideWhenEmbedded": true` results in a error.

**To Reproduce**
1. Config the mapmenu to `"hideWhenEmbedded": true`
2. Open the map embedded
3. Results in a error for example when adding sharemap or print control to the menu

**Expected behavior**
The map shouldn't cause errors when adding object to hidden menu.

**Comment by Grammostola** [comment]
> The map shouldn't cause errors when adding object to hidden menu.

This is the gist of a slightly broader subject that is related to the documentation, i.e the menu isn't added rather than merely hidden. The documentation for sharemap for instance does mention that "requires mapmenu control", same for print.

For the About control the description of `hideWhenEmbedded` is 
> if set to true, the control is not displayed when the map is embedded. Defaults to false

for most others it is
> if set to true, the control is not added when the map is embedded. Defaults to false.

Afaia the viewer will
```js
  const addControl = function addControl(control) {
    if (control.onAdd && control.dispatch) {
      if (!control.options.hideWhenEmbedded || !isEmbedded(this.getTarget())) {
        this.addComponent(control);
      }
```

that is to say not add a control that has the hideWhenEmbedded property and the map is embedded.

I wonder if it would not be better to add these controls but hide them via css / potentially some other adjustments per control when embedded map instead of not adding them to the viewer? There may be instance where the functionality should be present but not the UI.

**Comment by johnnyblasta** [comment]
Yes, I think it would be better to add the control, but hide it rather than just not add it at all.
