### ISSUE TITLE
Layer info menu - expected behavior?

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo#1640]
**Is your feature request related to a problem? Please describe.**
The behavior of the layer info menu is still a little bit confusing. Shouldn't the layer info menu close when you click "Zooma till" or "Spara ner lager"? The menu is still open if you click on either of the two options. It closes if you click the more option button again or do something else in the legend like expanding a group or making a layer visible.

I think the menu should close when clicking "Zooma till" or "Spara ner lager" or is there a reason for current behavior?

![layer-info-menu](https://user-images.githubusercontent.com/17123002/208651598-9ee438f0-aa71-4780-a551-e3e0ac6a88d9.gif)

**Comment by tonnyandersson** [comment]
I don't think there's a specific reason for the current behavior. But I agree that the menu should close after clicking an option inside, I think, mainly because it's more annoying to have to close it manually every time you open it than it is to re-open it the few times you want to use several of the tools inside on the same layer. So, I vote for close-on-click.

**Comment by jokd** [comment]
@asemoller Can we close this since  #1910 is merged?
