### ISSUE TITLE
cannot save image in the child table for a related layer

### ISSUE THREAD

**Issue by leafisfalling** [origo-map/origo#1757]
**Describe the bug**
Hello, 
We have a related-table layer in Origo 2 and we tried to save images into a column in our Postgres database childtable but it seems it does not work (while other attributes work perfectly in the same table). 
There is no problem to upload the picture in the editing formula, it looks like this: 

![image](https://user-images.githubusercontent.com/36880995/235098607-46f53726-8271-47e7-9327-aba77fd698dc.png)

But when we click “OK” to save the picture then it disappears, and nothing is saved in the database table.

**Comment by steff-o** [comment]
This is most likely a bug for which there is no workaround. When the form is closed an asynchronous operation is performed to resize the image and that changes the order of execution making the editor change active layer to the parent layer before the child layer is saved.

The code must be fixed by performing the same logic in in the resolve callback or rewrite to an async-await or move the resizing to the upload phase.

**Comment by steff-o** [comment]
I will have a look at this.
