### ISSUE TITLE
Print loading no visual feedback

### ISSUE THREAD

**Issue by filleg** [origo-map/origo#1871]
**Describe the bug**
When printing a PDF you get no feedback that work is being done in the background. Using a higher DPI or other settings that are demanding it can be mistaken for that something has gone wrong and the user tries to reload the page etc. 

**To Reproduce**
1. Print a A3 PDF in 300 DPI

**Expected behavior**
Some kind of spinner maybe, open for suggestions.  

**Additional context**
The possibility to abort a print would also be nice, without having to reload the page.

**Comment by Grammostola** [comment]
Visually: The blue progress bar from the main map and control "progressbar"? It is a known quantity for showing the progress of tiles of a map loading. Since the print preview map is always visible currently then the mentioned progressbar would always be also and seems fitting (the two buttons would re-enable when the progress was complete). If so then logically: it isn't currently wired to be reused wherever and would need adapting to be more generalized in terms of which map and where to be drawn.
