### ISSUE TITLE
Print legend bug

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#1952]
**Describe the bug**
When the sld in Geoserver is missing the Name property or if it is empty, it won't render the symbol in the print legend.

```
<sld:Rule>
          <sld:Name>anything goes</sld:Name>
          <sld:Title>Golvhöjd</sld:Title>
...
</sld:Rule>

<sld:Rule>
<sld:Title>Sockelrand</sld:Title>
...
```

![image](https://github.com/origo-map/origo/assets/6848075/70b74c5c-d3f3-42d3-a000-9a296e0b1d10)

However in the legend it looks better:
![image](https://github.com/origo-map/origo/assets/6848075/c4359ca4-610b-4368-9065-cfef09dd473f)

**Expected behavior**
Render the print legend even if the Name-property is missing.

**Environment:**
Geoserver

**Comment by Grammostola** [comment]
[getLegendGraphic ](https://docs.geoserver.org/latest/en/user/services/wms/get_legend_graphic/index.html) needs a `rule` param with a name value in order to fetch individual rules of a theme legend and I fail to see how we would get around that. (It is what's currently wrong with the css  extension for Geoserver but that's a different story)

**Comment by jokd** [comment]
I didn't look deep in the code but rather thought we could just iterate through the getlegendgraphic json and pipe out the image and title a bitt differently than today but obviously there is more to it. =)

**Comment by jokd** [comment]
Pretty much the same as #1921 so I close this as well
