### ISSUE TITLE
New class in _flex.scss

### ISSUE THREAD

**Issue by Dalneberg** [origo-map/origo#1976]
**Is your feature request related to a problem? Please describe.**
I am working on a plugin that should add a button to navigation tools/map tools and that should fold out a row of buttons on the right.
The problem is that I can not use both flex column and flex row for buttons in the same tool without them being affected by each other, i.e. so that the buttons keep the same size.

**Describe the solution you'd like**
A new class needs to be created in _flex.scss

In the new class that is proposed to be called .flextoolsleft, you need to define this

```css
.flextoolsleft {
    display: flex;
    align-items: flex-start;
    width: 35px;
```

The rest of the code should be the same as in the class .flex

This below also then needs to be changed in main.js for the tools that should use it. For this purpose in the navigation och maptools that are placed in o-tools-left

Row 9 och 10:
```js
const navigation = El({ cls: 'o-navigation flextoolsleft column relative transparent spacing-vertical-small' });
const mapTools = El({ cls: 'o-maptools flextoolsleft column relative transparent spacing-vertical-small' });
```

Row 21:
```js
<div id="o-tools-left" class="box top-left transparent flextoolsleft column">
```

**Describe alternatives you've considered**
I have tried to use the class flex but it is not working

**Additional context**

**Comment by tonnyandersson** [comment]
Hi @Dalneberg!

Would it be sufficient to just add the class `align-start` to the map tools and navigation tools containers? Like this:

```javascript
const navigation = El({ cls: 'o-navigation flex column relative transparent spacing-vertical-small align-start' });
const mapTools = El({ cls: 'o-maptools flex column relative transparent spacing-vertical-small align-start' });
```

**Comment by Dalneberg** [comment]
Hi @tonnyandersson, yes good idea! if I also adds style: 'width: 35px; it would be sufficient. Like this:

```js
const navigation = El({ cls: 'o-navigation flex column relative transparent spacing-vertical-small align-start', style: 'width: 35px;' });
const mapTools = El({ cls: 'o-maptools flex column relative transparent spacing-vertical-small align-start', style: 'width: 35px;' });
```

If I don´t also add style: 'width: 35px; the buttons in the same div will get the width of the entire mapviewlist button and its sub-buttons, i.e. the tooltip for the other buttons ends up far to the right.

But with this change above in main.js I don't have to create a new class in _flex.scss.

**Comment by tonnyandersson** [comment]
@Dalneberg Can you provide an example (screenshot/GIF/whatever) of what you are trying to achieve? The thing is, I can't quite see the point of adding the seemingly arbitrary yet very specific width of 35px.

If I understand you correctly, you are trying to achieve something like this:

![image](https://github.com/origo-map/origo/assets/15725608/f75f1502-b615-4e2c-8354-11fa5429596f)

...and for that, there's no need to add 35px anywhere.

**Comment by Grammostola** [comment]
The problem seems to be that when something wide, like a grid is put into either flexbox (maptools or navigation) in the northwest quadrant they will flex to accommodate (become wider), which as @Dalneberg mentioned shifts the tooltips for the existing inhabitants of said quadrant (measure, home etc) far into the east (slightly east of 'wide'), because the tooltips aren't centered on the inhabitant buttons as these buttons aren't positioned. 

The (potentially separate)  issue appears resolvable by adding `position: relative` to the existing buttons, without other position arguments they shouldn't be disturbed.

**Comment by tonnyandersson** [comment]
Ah, you're right. I overlooked the part about the tooltips.

I like the `position: relative` solution better than "hardcoding" a specific width, given that it doesn't eff up something else.

I suggest adding the classes below to _viewer.scss instead of adding it to each separate button. Unless anyone has got a more elegant solution at hand.

```css
.o-navigation button {
  position: relative;
}

.o-maptools button {
  position: relative;
}
```
