### ISSUE TITLE
Create a toaster for messages

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#1982]
**Is your feature request related to a problem? Please describe.**
We should have a simple way to show messages for the user, eg when a request fails or something is saved.

**Describe the solution you'd like**
We have a toaster for the infowindow exporthandler that could be moved to utils and be used by other functions. Perhas it also needs some kind of overhaul to be useful in a more general way.

**Comment by asemoller** [comment]
@jokd You just took my "soon-to-submit-issue"! 😸

I agree and we have a plugin in progress that needs this function.

**Comment by jokd** [comment]
> @jokd You just took my "soon-to-submit-issue"! 😸
> 
> I agree and we have a plugin in progress that needs this function.

Cool. Any input on how to design it or what features it should have? 
The current one slides in from top right corner of the window and is shown for five seconds and then disappear and you can feed it with either a success or failmessage. I would like it a bit more configurable.

**Comment by tonnyandersson** [comment]
Mentioning https://github.com/origo-map/origo/issues/662 for the record.

**Comment by asemoller** [comment]
> Cool. Any input on how to design it or what features it should have?
> The current one slides in from top right corner of the window and is shown for five seconds and then disappear and you can feed it with either a success or failmessage. I would like it a bit more configurable.

Yes, a little more configurable is a good one! Duration for example.

Then we have the discussion about whether a toaster or a modal is the best way forward for messages (for the user). I guess there are pros and cons to both. Whatever choice is made, it should be consistent in Origo.

**Comment by jokd** [comment]
> Then we have the discussion about whether a toaster or a modal is the best way forward for messages (for the user). I guess there are pros and cons to both. Whatever choice is made, it should be consistent in Origo.

I guess that should be configurable as well. A modal can eg be a bit verbose for some situations.

**Comment by steff-o** [comment]
I actually opted out of toasters in MultiSelect-plugin a couple of weeks ago as I didn't have time to implement a general toaster i the core. Instead I choose a clean Modal, which is already exposed instead of creating a one off implementation of a toaster in Multiselect.

That said, I'm all for it. I think the toaster should be exposed in the api as a function , e.g. showToaster(), which takes some arguments:
- Duration
- Title
- Message
- Severity (error, warning, OK,  info)
- Possibly an icon

Everything except "message" should have sensible defaults.

Whether to use toaster or modal I think is up to each control and add its own configuration if anything needs to be configured. Possibly a global duration setting and default icons for each severity could be useful.

**Comment by jokd** [comment]
> I actually opted out of toasters in MultiSelect-plugin a couple of weeks ago as I didn't have time to implement a general toaster i the core. Instead I choose a clean Modal, which is already exposed instead of creating a one off implementation of a toaster in Multiselect.
> 
> That said, I'm all for it. I think the toaster should be exposed in the api as a function , e.g. showToaster(), which takes some arguments:
> 
> * Duration
> * Title
> * Message
> * Severity (error, warning, OK,  info)
> * Possibly an icon
> 
> Everything except "message" should have sensible defaults.
> 
> Whether to use toaster or modal I think is up to each control and add its own configuration if anything needs to be configured. Possibly a global duration setting and default icons for each severity could be useful.

Great input. I'll start cooking.
