### ISSUE TITLE
WMS getLegendGraphic option

### ISSUE THREAD

**Issue by MahnazN** [origo-map/origo#258]
Make WMS type layer definitions not require style: , if style is supplied for WMS type layers then it defines an alternative style; use getLegendGraphic for the legend.

**Comment by tonnyandersson** [comment]
We have a solution in place in a pre-Origo version of the code. Never used it in production, though, and I'm not sure it can handle more advanced styling in a good way. But it's a start. I can modify it and provide an example, unless anyone else already have a working solution at hand.

**Comment by tonnyandersson** [comment]
@MahnazN @afogelberg PR is up.

**Comment by Grammostola** [comment]
Sweco made changes in the Summer of '17 to mostly legend.js of our fork to make the map load without style: for wms layers, and for "WMS" type layers to be able to be configured so: 
"New properties for WMS-layer:
{bool} useLegendGraphics
{string} legendGraphicsType ("inline", "toggleable")
{object} legendGraphicSettings (http://docs.geoserver.org/latest/en/user/services/wms/get_legend_graphic/index.html)
" where legendGraphicSettings makes a few options possible and "inline" means on same row as layer title and checkbox and "toggleable" a vertical disclosure arrow, suitable for themed legends.  
![bild](https://user-images.githubusercontent.com/5138906/40498126-66caa0ac-5f7e-11e8-91ae-54586f4ebdc8.png)

where "Områdesbestämmelser" is:
                                        "name": "sokvyx_detaljplan_planomryta_20_omradesbest",
                                        "title": "Områdesbestämmelser",
                                        "group": "bygga",
                                        "queryable": true,
                                        "type": "WMS",
                                        "visible": false,
                                        "source": "etuna",
..
                                        "useLegendGraphics": true,
                                        "legendGraphicType": "inline"
                                      },
https://github.com/Eskilstuna-kommun/EK-extern/commit/bbdd450bbfb26e03cf2e15ed3eca6afab0aa3327

In order to accomodate styles having scale variations new getlegendgraphic-calls were later made to be made on each zoom on the basis that they aren't fetching large amounts of data.

WMS layers can still use style: instead of legendGraphics (not for an alternative WMS-sld-style, rather for a traditional Origo style) if one wishes. (Themed and scale dependant and polygon and line styles we tend to use legendGraphics for)

**Comment by tonnyandersson** [comment]
Outdated. Will probably be reworked and posted as new issue.

**Comment by Grammostola** [comment]
New issue pending reply on geoserver-users email list, i.e whether one getLegendGraphic call can be made per layer to get the styles as json (for every scale).

**Comment by Grammostola** [comment]
No new issue as https://github.com/geoserver/geoserver/wiki/GSIP-173 - maxScaleDenominator and min are not part of the returned legend json (one is meant to specify a scale when asking for it). So one getlegendgraphic call would have to be made per zoom step.
