### ISSUE TITLE
WMS GetFeatureInfo text/html option

### ISSUE THREAD

**Issue by MahnazN** [origo-map/origo#259]
Provide text/html return option in WMS layer definition for getFeatureInfo requests

**Comment by Grammostola** [comment]
Sweco developed a WMS layer config option for info_format: 

http://docs.geoserver.org/stable/en/user/services/wms/reference.html

https://github.com/Eskilstuna-kommun/EK-extern/commit/cad3d92c9aecceb93239f14c1803b1d941897005

(we use it for text/html for freemarker template usage and info popup definitions are therefore separated from map jsons)

**Comment by Bimane1900** [comment]
I have looked into this a bit as of Origo v2.2. 
The way I see it, it seems to require a bit of changes here and there due to the code that handles featureinfo clicks often assumes an Openlayers Feature. A text/html response does not return anything that could be turned into such a feature.  
It is quiet simple to handle the missing feature by defining a new feature and setting the text/html response as an attribute that the featureinfotemplate code can handle, but it seems like a quick-fix solution and not a real one.

**Comment by Grammostola** [comment]
Currently we have left the change/addition to the core delineated so that potential future conflicts are easier to handle. The question of text/html touches the question of map server type and map server type potentially relates to more WMS operations than getFeatureInfo.

**Comment by Grammostola** [comment]
Following our discussion regarding this issue on this week's tuesday I received recommendations to always fetch geometry even if it means an extra fetch.
Following this I've run into things requiring a clarification and a question  regarding ArcGIS WMS layers and their (default) text/html response.

- The question: Their default text/html response is the familiar blue and white horizontal table. It works fine in an infowindow and an overlay however it does not work very well in an overlay carousel as the cards therein will not show a horizontal scroll bar. Yes the table can be altered by the client but the info templates can be changed serverside. The way I see it we can: Change the overlay carousel to show a horizontal scrollbar; assume a default info template from an AGS and make the table vertical; not make text/html compatible with ArcGIS Server WMS services as the application/geo+json is generally preferrable.
- The clarification:  In order to fetch the geometry of the corresponding AGS map service the AGS WMS layer needs two additional properties, the id of the map layer and the attribute to identify a feature via. 

So shall we try and get this working with Geoserver and potentially QGIS server first or do you see a viable solution for (and a real need of) AGS WMS text/html?
