### ISSUE TITLE
Scale picker

### ISSUE THREAD

**Issue by tonnyandersson** [origo-map/origo#393]
Dropdown scale picker control that lets the user set map scale from a list of given scales.

**Comment by daRasmussen** [comment]
Scale picker is depended of scale line and should not be enabled without a proper reference. The scale picker feature should be implemented in the print controller. If Origo provides scale as a controller users might measure lengths and sizes directly on the screen. But that is not accurate since DPI determine the base unit, hence a scale picker is directly depended of a scale line. And Origo is a webbmap used on the webb, user that perfer analog measure tools should not use Origo. They should use printed maps constructed in CAD, AGIS or QGIS...
