### ISSUE TITLE
Suggested option 'fit' for layers

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#494]
I would like to introduce the 'fit'-option for layers that would override the map settings and zoom and pan to a specific layers content. This way we could use a dynamic webservice as layer source. Is this perhaps somehow incorporated already?

**Comment by tonnyandersson** [comment]
Sounds like a great idea! AFAIK, there is currently no similar function implemented other than what you get with a permalink. BUT - and please correct me if I'm wrong - that would not work well with WMS layers since there is no function to get the extent directly from the layer or source object. You'd have to get that information from the capabilities document. I could be wrong, but I got stuck on this when researching possibilities for a Zoom to-function in the layers panel.

**Comment by jokd** [comment]
Makes sense. Perhaps the option is just for vector layers?

**Comment by afogelberg** [comment]
Well, we could include it for raster layers as well, since there's an option ta define an extent manually for all layers. And if that extent is not given, it will default to the map extent. It will not be 100% accurate of course, but I think it's better than excluding all raster layers.

**Comment by tonnyandersson** [comment]
Good point, @afogelberg.

**Comment by tonnyandersson** [comment]
@jokd Are you working on this?

**Comment by jokd** [comment]
Not at all but I might have a go at it soon. Too good idea to throw in the bin.

**Comment by tonnyandersson** [comment]
Cool.

We added a new label - _archived_ - for issues that are too good to just close and forget but not planned to be developed in the near future. That way we can label them and close them to keep the issues list more relevant and still be able to easily filter out the goodies in the closed section.
