### ISSUE TITLE
Show in legend if layer is within visible zoom levels

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#499]
If a layer is not within visible zoom levels, it should be indicated in the legend, for example by greying out the layer icon.

**Comment by asemoller** [comment]
This would be a very useful function for the user. When utilizing zoom dependent layers it can be confusing when there is no indicator to tell the user if there is a active layer that is now non-visible due to the current zoom level. Also an indicator that tells if you need to zoom out or in on specific layers would be useful.
