### ISSUE TITLE
Keyboard navigation 

### ISSUE THREAD

**Issue by daRasmussen** [origo-map/origo#667]
It would be nice if it was possible to navigate the map with arrow keys.

**Comment by johnnyblasta** [comment]
The map is already enabled for navigation with arrow keys or am I missing some point?
If you press "tab" key or zoom-in, so the origo-map is in focus it's possible to navigate with arrow keys.
Is this issue meant to fix, so that the map is in focus at start, so you don't have to do an extra action to make it work?

**Comment by jokd** [comment]
It should be automatic I think. Or at least make it more intuitive like a click in the map.

**Comment by daRasmussen** [comment]
The default behavior could be that navigation with arrows is enabled without the "tab" key. 

Regarding arrow navigation and "tab" fixes in general: 
- Zoom in and zoom out is focused the UI does not correspond to that state.
- Home button does get focused, which it did in v1.0.0.
- Measure controller - does not support arrow keys.
- Escape key does not work on share map.
- Share, print, about, link does not get highlighted.
- Switching layers and bakground maps are not supported.

**Comment by mulfvik** [comment]
I agree with @daRasmussen The default behavior, and when focused on map id, should listen to openlayers key events. Otherwise not.

**Comment by mulfvik** [comment]
When editor form is open and you use ol navigation keys the map navigates, it is not typing in the letter in the form.
