### ISSUE TITLE
Close button sometimes interpreted as click

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#723]
Clicking the close button of a popup window is sometimes interpreted as a click in the map and triggers another popup.

**Comment by MattiasSp** [comment]
This seems to work well on desktop, however when I try on mobile (Chrome on Android) the old behaviour seems to remain. Reopen if you agree?

**Comment by jokd** [comment]
I cannot test your setup since I use iOS, but Chrome on iOS works well. 
I reopen the issue and perhaps someone else can have a look.
What version of Origo are you testing against?

**Comment by Grammostola** [comment]
I will see if I can reproduce it with the latest Origo, sometime next week.

**Comment by Grammostola** [comment]
@MattiasSp Hi Mattias, what version of Origo did you experience the issue with? Can you reproduce it with the latest Origo? I tried it now with a Pixel 1, Android 10, default Origo (devel server) (default index.json) Chrome and FF and manually tapped 50+ times in each on an 'x' of a popup where that x was precisely over another poi (so that another tap produced a popup) , on different zoom levels and landscape as well as portrait and I was unable to repro the issue.

**Comment by jokd** [comment]
Close this for now
