### ISSUE TITLE
Legend styling issue

### ISSUE THREAD

**Issue by jokd** [origo-map/origo#797]
Setting the legend width doesn't always alter the width of the content.

![image](https://user-images.githubusercontent.com/6848075/72335406-37244a00-36bf-11ea-81b7-a14e371f4ee7.png)

**Comment by tonnyandersson** [comment]
This is not a bug, I think. This may be because the way the legend is made up. The legend control takes (among others) two style parameters - style _and_ contentStyle. To set a custom width, you need to set both to change the width of the legend and its contents. Like this:

![image](https://user-images.githubusercontent.com/15725608/72428911-fe53a600-378e-11ea-94e7-2136b184f16a.png)

**Comment by jokd** [comment]
Then you actually just have to set contentStyle to alter the width of the legend, right?

**Comment by jokd** [comment]
I changed the documentation to clarify this.
