### ISSUE TITLE
New build for embedded maps

### ISSUE THREAD

**Issue by afogelberg** [origo-map/origo#83]
I suggest that Origo offer an alternative build that can be used for embedded maps. This build would be very simple with only basic functionality such as zoom and open map in full extent. The same configuration file could be used as for the ordinary, but ignoring the control options. Jsonp should be used to get the configuration file as suggested in #70 . With a separate build we could also have a significant smaller build size.

**Comment by afogelberg** [comment]
I have been working on this issue and suggest some changes to make it easier to have separate builds. I suggest that the controls are initiated in the main files and not in the viewer. This means that all controls to be included in the build should be listed in the main files. The main file for origo will still be origo.js but for a separate build we need to have a separate one. I have created a branch where I have implemented these ideas: https://github.com/origo-map/origo/compare/origo-embed

These I think are some important changes. Some opinions on this would be appreciated @markus659 @jokd . If you think this is the way to go I will continue the work. So far there is still only one build.

**Comment by markus659** [comment]
Would all configuration still be in the .json file? Looking at your branch, would all the controls still be included in the origo.min.js-file, or would the ones that are not included not be a part of the minified file (or would you need to manually edit the origo.js file if you don't want them included at all)? 

What would be the difference between the different builds, only the origo.js-file and what controls are included in that file?

Maybe only OL-controls should be in the viewer, meaning the home button should also be part of the Origo controls? See issue #76.

**Comment by jokd** [comment]
I definitely see good use for this and just editing origo.js instead of viewer.js for separate builds is something to strive for.


Från: Andreas Fogelberg [mailto:notifications@github.com]
Skickat: den 23 september 2016 16:57
Till: origo-map/origo <origo@noreply.github.com>
Kopia: Jonas Kumlin <jonas.kumlin@karlstad.se>; Mention <mention@noreply.github.com>
Ämne: Re: [origo-map/origo] New build for embedded maps (#83)


I have been working on this issue and suggest some changes to make it easier to have separate builds. I suggest that the controls are initiated in the main files and not in the viewer. This means that all controls to be included in the build should be listed in the main files. The main file for origo will still be origo.js but for a separate build we need to have a separate one. I have created a branch where I have implemented these ideas: https://github.com/origo-map/origo/compare/origo-embed

These I think are some important changes. Some opinions on this would be appreciated @markus659<https://github.com/markus659> @jokd<https://github.com/jokd> . If you think this is the way to go I will continue the work. So far there is still only one build.

**Comment by afogelberg** [comment]
> Would all configuration still be in the .json file?

Yes. But if the control is not included in the build it will not be added.
> would all the controls still be included in the origo.min.js-file, or would the ones that are not included not be a part of the minified file (or would you need to manually edit the origo.js file if you don't want them included at all

Only the controls required in the main file for the build would be included in the minified file. This means that we can get smaller builds. If you want to have a control included in the build just require it in the main file and it will be available.  
> Maybe only OL-controls should be in the viewer, meaning the home button should also be part of the Origo controls?

I agree

With these changes it will be easier to make custom builds with smaller size. In the main file we can also turn on and off proj4 for the build. What will really reduce the build size is using custom builds of ol3. I'm not sure have we should handle those in Origo. If we make a build file for ol3 and place it in the ol3 package it will not be included in the origo repo. Any suggestions on have we should handle ol3 builds?

**Comment by afogelberg** [comment]
I'm closing this now as I would say that all pieces are in place to make small customized builds for embedded maps. Although embedded maps will work better with #216 and #105 .
