### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by Abelon38** [origo-map/origo#855]
Hi!

I get a problem with ÄÖÅ when sharing the map. Is there a Hotfix to this issue we could implement?
![image](https://user-images.githubusercontent.com/12575941/76205793-39a4ab00-61fb-11ea-8487-fa8fa0c108e4.png)

Vi är using Origo v2.1.0

Thank you for your time!

**Comment by tonnyandersson** [comment]
Hi, @Abelon38!

Try changing the `meta charset` in *index.html* or add a `charset` parameter when loading the *origo.js* script. **Try with different charsets**.

Like:

`<meta charset="utf-8">`

or

`<script src="js/origo.js" charset="utf-8"></script>`

Not sure if any of them will work, though, because I think you may be using a different character encoding in your text editor of choice. My suggestion is to always make sure your edits are in UTF-8, since that's the standard encoding used by Origo.

**Comment by tonnyandersson** [comment]
Closing this issue since Origo is not the source of the problem.

**Comment by tonnyandersson** [comment]
Closing this issue since Origo is not the source of this problem.

**Comment by mulfvik** [comment]
@Abelon38 Did you solve this issue?

**Comment by tonnyandersson** [comment]
@mulfvik This issue can be closed since Origo was not the source of the problem. Tried to close it before, but it did not want to close. Trying again.
