### ISSUE TITLE
Origo could have an translation object/config

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo#900]
Origo could have an translation object where there can be a choise to have it empty aswell. In that case the user can define for themself labels, tooltips etc. for the whole framework and Origo only mangage defaults.

_Originally posted by @mulfvik in https://github.com/origo-map/origo/issues/898#issuecomment-611006359_

**Comment by Grammostola** [comment]
Like in supporting different locales (localization) instead of hard coding Swedish strings? That makes sense for an international development but does require translation and perhaps supported languages so my sense is that you are rather referring to the first part of that:: UI strings are objects with ids and there's an easily accessible place to replace any default values with whatever a user would wish for. Like " 'Transparens' is nice but 'opacitet' is what I would prefer for this map". This would seem like a pleasant addition.

**Comment by mulfvik** [comment]
What!! Do you prefer "opacity"?? ;)
Could have an url definition in index.json that point to a translation.json? Defaults to english with swedish translated and you can change the swedish to prefered language or whatever.

**Comment by Grammostola** [comment]
I have strictly no opinion on that specific matter : ) 

If we are indeed talking about localization then languages tend to come and be requested more or less complete, i.e "100% of the original strings have been translated to Spanish" and there's work in maintaining those for each release, including testing to see whether they are clipped in the UI etc and perhaps numeral locale considerations too. That is unless popular translations ("Spanish" for instance) are volontary, reside somewhere else and is a separate responsibility from Origo.

**Comment by mulfvik** [comment]
Yes, so Origo defaults to english and supply translation for swedish. User may define own translation and update new strings in translation.json, or not, the strings that is not translated default to english. In this way the codebase stays in english. If you want it in spanish, use the translation object man ;)

**Comment by Grammostola** [comment]
For an internationalization effort it may make sense to keep the default strings US English. That end users/admins of maps can edit their own jsons for translations seems accessible enough. If said users/admins were to make an effort and supply a Finnish translation for all the Origo default US English strings I imagine it would be good if said json was easily found in connection with the Origo client, even if it isn't supplied with the Origo client, so that thirteen different people all over Finland aren't working on translating their own json in parallell and so that our Readme.md can say "News! Thanks to ... and ...Origo is now available in Finnish". Or some such :  )
